url = env.get("URL")
pp(url)
aR = ajax({ url }).aR()
title = aR.getString("title@text")
result = aR.getString("class.tpc_cont@img@ess-data")
pp(title)
pp(result)
saveFile("/opt/urls.txt", result)
shell.run("wget -i /opt/urls.txt -P /opt/catvod/output")
shell.run(`echo "UPLOAD_NAME=${title}" >> $GITHUB_ENV`)
