name: Build Asynqmon Windows

on:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: hibiken/asynqmon
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install NPM packages
        run: cd ui && rm yarn.lock && yarn install
        
      - name: Build Release Binary
        run: |
          GOOS=windows GOARCH=amd64 make build
          ls
          
      - name: upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: asynqmon_windows_amd64
          path: asynqmon
