name: Build Jupyterlite

on:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jupyterlite/demo
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
        
      - name: Build the JupyterLite site
        run: |
          cp README.md content
          jupyter lite build --contents content --output-dir dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
