name: Build Yarr Linux

on:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: nkanaev/yarr
          submodules: 'recursive'
          
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          
      - name: Build
        run: |
          CGO_ENABLED=1 go build -tags "sqlite_foreign_keys release linux" -ldflags '-extldflags -static' -o yarr src/main.go
          
      - name: upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: yarr_linux
          path: yarr
