name: Build Jupyterlite

on:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jupyterlite/demo
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install numpy
          pip install ipydrawio[all]  
          pip install jupyterlab-spreadsheet-editor
          
      - name: Build the JupyterLite site
        run: |
          wget https://github.com/pyodide/pyodide/releases/download/0.27.6/pyodide-0.27.6.tar.bz2
          cat > ./repl/jupyter-lite.json <<EOF
          {
            "jupyter-lite-schema-version": 0,
            "jupyter-config-data": {
              "litePluginSettings": {
                "@jupyterlite/pyodide-kernel-extension:kernel": {
                  "pyodideUrl": "./static/pyodide/pyodide.js"
                }
              }
            }
          }
          EOF
          cp README.md content
          jupyter lite build --pyodide pyodide-0.27.6.tar.bz2 --contents content --output-dir dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
