name: Build Redis Windows

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'version to build'
        required: true
        default: "7.0.8"
        type: string
jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3
      - name: Version
        run: |
          Invoke-WebRequest -Uri https://github.com/redis/redis/archive/refs/tags/${{ inputs.tag_name }}.tar.gz -OutFile redis-${{ inputs.tag_name }}.tar.gz
          tar -xvf redis-${{ inputs.tag_name }}.tar.gz
        shell: pwsh

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: gcc make pkg-config mingw-w64-x86_64-python
      - name: Build Redis
        if: ${{ success() }}
        run: |
          workspace=$(pwd)
          sed -i 's/__GNU_VISIBLE/1/' /d/a/_temp/msys64/usr/include/dlfcn.h
          cd redis-${{ inputs.tag_name }} && make -i PREFIX=$workspace/dist install
          cp /d/a/_temp/msys64/usr/bin/msys-2.0.dll redis.conf sentinel.conf $workspace/dist/bin/
          cd $workspace/dist/
          mv bin Redis-${{ inputs.tag_name }}-Windows-x64
          tar -cvzf $workspace/Redis-${{ inputs.tag_name }}-Windows-x64.tar.gz Redis-${{ inputs.tag_name }}-Windows-x64/*

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.tag_name }}
          path: |
            Redis-${{ inputs.tag_name }}-Windows-x64.tar.gz
