# This is a basic workflow to help you get started with Actions

name: climages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#   schedule:
#     - cron: '0 3 * * *'
  # watch:
  #   types: [started]
  workflow_dispatch:
    inputs: 
      url: 
        description: 'url'      
        required: true 
        default: 'https://cl.6939x.xyz/htm_mob/2302/7/5542122.html'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: run
      shell: bash
      env:
        URL: ${{ github.event.inputs.url }}
      run: |
        mkdir -p /opt/catvod/data
        cd /opt/catvod/
        mkdir output
        wget https://github.com/10bits/github-actions-test/releases/download/catvod-JSRE/catvod-linux-x64
        chmod +x ./catvod-linux-x64
        cp $GITHUB_WORKSPACE/climages.js /opt/catvod/data/
        ./catvod-linux-x64 <<EOF
        loadScript("climages.js")
        EOF
    - name: upload artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: ${{env.UPLOAD_NAME}}
        path: /opt/catvod/output
