# This is a basic workflow to help you get started with Actions

name: git lfs download

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: git lfs pull
        shell: bash
        run: |
          mkdir -p /opt/repo
          cd /opt/repo
          git clone --no-checkout https://github.com/zengguocheng/e-book
          cd e-book
          git lfs pull --include "操作系统/ORANGE’S：一个操作系统的实现/*"
          
      - name: upload artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: repo
          path: /opt/repo
