name: Build SRS Windows

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'version to build'
        required: true
        default: "5.0-b6"
        type: string
jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3
      - name: Version
        run: |
          Invoke-WebRequest -Uri https://github.com/ossrs/srs/archive/refs/tags/v${{ inputs.tag_name }}.tar.gz -OutFile srs-${{ inputs.tag_name }}.tar.gz
          tar -xvf srs-${{ inputs.tag_name }}.tar.gz
        shell: pwsh

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: gcc make pkg-config mingw-w64-x86_64-python
      - name: Build SRS
        if: ${{ success() }}
        run: |
          workspace=$(pwd)
          mkdir dist
          cd srs-${{ inputs.tag_name }}/trunk
          ./configure --full --prefix=$workspace/dist
          make install
          cp /d/a/_temp/msys64/usr/bin/msys-2.0.dll $workspace/dist/objs
          tar -cvzf $workspace/SRS-${{ inputs.tag_name }}-Windows-x64.tar.gz $workspace/dist/*
