# This is a basic workflow to help you get started with Actions

name: Update IPv6

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs: 
      url: 
        description: 'ipv6'      
        required: true 
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: run
      shell: bash
      env:
        IPV6: ${{ github.event.inputs.ipv6 }}
        CHACHA20KEY: ${{ secrets.chacha20key }}
        CHACHA20NONCE: ${{ secrets.chacha20nonce }}
      run: |
        mkdir -p /opt/catvod/data
        cd /opt/catvod/
        mkdir output
        wget https://github.com/10bits/github-actions-test/releases/download/catvod-JSRE/catvod-linux-x64
        chmod +x ./catvod-linux-x64
        cp $GITHUB_WORKSPACE/*.js /opt/catvod/data/
        ./catvod-linux-x64 <<EOF
        loadScript("ipv6.js")
        EOF
